class AppImages {

  static const splashLogo = "assets/images/logo.png";
  static const chatIcon = "assets/icons/chat_icon.png";
  static const onboardingflower = "assets/images/onboarding/onboarding_flower.png";
  static const gentler = "assets/images/onboarding/a_gentler.png";
  static const tapcard = "assets/images/onboarding/tap_card.png";
  static const backcard = "assets/images/onboarding/back_card.png";
// ============= app icons===========
  static const daimondicon = "assets/icons/onboarding/daimond.png"; 
  static const checkmark = "assets/icons/onboarding/check_mark.png";
  static const couples = "assets/icons/onboarding/couples.png";
  static const person = "assets/icons/onboarding/person.png";
  static const family = "assets/icons/onboarding/family.png";
  static const self = "assets/icons/onboarding/self.png";
  static const arrowbuttonicon = "assets/icons/card_interation/arrow_button.png";
  static const foucsarrow = "assets/icons/card_interation/foucs_arrow.png";
  static const heart = "assets/icons/card_interation/heart.png";
  static const finallogo = "assets/images/card_interation/finallogo.png";
  static const home = "assets/icons/card_interation/home.png";
  static const team = "assets/icons/card_interation/team.png";
  static const emoji = "assets/icons/card_interation/emoji.png";
  static const oo = "assets/icons/pay_wall/o.png";
  static const exclusiveimage = "assets/icons/pay_wall/Exclusive.png";
  static const blackheart = "assets/icons/pay_wall/blackheart.png";
  static const google = "assets/icons/authentication/google.png";
  static const apple = "assets/icons/authentication/apple.png";
  static const email = "assets/icons/authentication/email.png";
  static const flowerimage = "assets/images/authentication/flowerimage.png";
  static const locked = "assets/icons/library/locked.png";
  static const greensavedcard = "assets/images/savedconversations/green_savedcard.png";
  static const brownsavedcard = "assets/images/savedconversations/brown_savedcard.png";
  static const bluesavedcard = "assets/images/savedconversations/blue_savedcard.png";
  static const backarrow= "assets/images/card_interation/backarrow.png";
  static const foucsarrowcardscreen ="assets/images/card_interation/backarrow.png";
  static const guestdotimage =  'assets/icons/authentication/guestmode.png';
  static const arrowdiamond = "assets/icons/authentication/arrowdiamond.png";
  static const cricle = "assets/icons/authentication/cricle.png";
  static const homeandarrow = "assets/icons/home";
  static const bigblackheart = "assets/icons/authentication/bigblackheart.png";
  static const backarrowwhite = "assets/images/card_interation/backarrow.png";
  static const foucsarrowwhitescreen = "assets/images/card_interation/focusarrow.png";
  static const closeicon = "assets/icons/authentication/close.png";
  static const lockimage = "assets/icons/authentication/lock.png";
  static const smallblackcricle = "assets/icons/profile/smallbalckcricle.png";
  static const smallblackheart = "assets/icons/profile/smallblackheart.png";
  static const notification = "assets/icons/profile/notification.png";
  static const setting = "assets/icons/authentication/setting.png";
}